### ISSUE TITLE
Search request not passed to Solr

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-dc#135]
So I have setup isle-dc with some test content. The content gets indexed into solr without an issue, that means the connection to solr is set up, but when searching, the request does not get passed to solr (no info in logs). Queries by hand return the correct search results.
So something happens within drupal that does not forward the request to solr.
I tried using search_api_solr_devel and it does not show anything on search, except in the admin interface it shows the requests.
This is the request thats made to drupal:
https://islandora.traefik.me/solr-search/content?search_api_fulltext=Lorem

**Comment by Tristaan** [comment]
Fixed it with configuration changes in the search view.

**Comment by DonRichards** [comment]
This is still an issue with the default build process and needs attention.
